#!/usr/bin/env bash

# Check if ruby command is available
if ! command -v ruby &> /dev/null; then
  echo "Error: Ruby is not installed. Please install Ruby >= 2.4 to continue."
  exit 1
fi

# Check if bundle command is available
if ! command -v bundle &> /dev/null; then
  echo "Error: Bundler is not installed. Installing bundler ..."
  bash -c "gem install bundler"
  # Run bundle install verbose
  bash -c "bundle install"
else
  # Run bundle install silently to install dependencies
  bash -c "bundle install > /dev/null 2>&1"
fi

bash -c "ruby /usr/share/goblin-doc/src/main.rb $*"